spring.application.name=sms_extract

server.port=8081

# event publisher
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.properties.retries=3
spring.kafka.producer.properties.acks=all
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer = com.example.sms.sms_extract.serializer.SmsInfoSerializer
spring.kafka.topic-json.name=expense_service_topic
logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG
spring.kafka.producer.properties.spring.json.type.mapping=auth:C:\Users\shiva\IdeaProjects\sms_extract\src\main\java\com\example\sms\sms_extract\dto\TransactionDetailsDTO.java
security.basic.enable= false
security.ignored=/**

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console for browser access at /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings to automatically create tables from your entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.ai.google.genai.api-key =${gemini_api}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash